--- #YAML:1.0
name:                OP
version:             0.310_001
abstract:            Compact prototyping of InnoDB-backed object classes
license:             open_source
author:              
    - Alex Ayars <pause@nodekit.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cache::Memcached::Fast:        0.13
    Carp:                          1
    Clone:                         0.29
    Data::GUID:                    0.043
    Data::Validate::Domain:        0.09
    Data::Validate::Email:         0.04
    Data::Validate::IP:            0.08
    Data::Validate::URI:           0.05
    Digest::SHA1:                  2.11
    Email::Address:                1.889
    Error:                         0.17015
    File::Copy:                    2
    File::HomeDir::Unix:           0.86
    File::Path:                    2.04
    File::Tempdir:                 0.02
    GlobalDBI:                     0.21
    IO::File:                      1.14
    JSON::Syck:                    0.29
    Lexical::Persistence:          0.98
    Math::VecStat:                 0.08
    Net::Syslog:                   0.03
    Parse::RPN:                    2.43
    Rcs:                           1.05
    Scalar::Util:                  1.19
    Sys::Hostname:                 1.11
    Term::ReadLine:                1
    Test::More:                    0.86
    Time::HiRes:                   1.9711
    Time::Piece:                   1.12
    Unicode::String:               2.09
    URI::Escape:                   3.29
    YAML::Syck:                    1.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
